# Generated by Django 4.2.6 on 2023-11-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_coupon_order_alter_product_photo_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
