# Generated by Django 4.2.6 on 2023-11-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_alter_coupon_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='invoice_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='invoice_city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='postal',
            new_name='invoice_postal',
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_country',
            field=models.CharField(default='Test', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='Test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(default='Test', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(default='Test', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_postal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='taxnumber',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
