# Generated by Django 4.2.6 on 2023-11-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_rename_address_order_invoice_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxnumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
